# noqa
# ruff: noqa
# type: ignore
"""more_problemset_metadata

Revision ID: 17288a5f8167
Revises: fd4be665eb58
Create Date: 2025-12-27 17:44:39.539374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "17288a5f8167"
down_revision: Union[str, Sequence[str], None] = "fd4be665eb58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("problemset", sa.Column("is_public", sa.Boolean(), nullable=False))
    op.add_column(
        "problemset",
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column(
        "problemset",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column("problemset", sa.Column("owner_id", sa.Uuid(), nullable=True))
    op.alter_column(
        "problemset", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_unique_constraint(
        "uq_problemset_owner_id_name", "problemset", ["owner_id", "name"]
    )
    op.create_foreign_key(None, "problemset", "user", ["owner_id"], ["id"])
    op.drop_column("problemset", "created_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "problemset",
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "problemset", type_="foreignkey")
    op.drop_constraint("uq_problemset_owner_id_name", "problemset", type_="unique")
    op.alter_column(
        "problemset", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("problemset", "owner_id")
    op.drop_column("problemset", "updated_at")
    op.drop_column("problemset", "tags")
    op.drop_column("problemset", "is_public")
    # ### end Alembic commands ###
