# noqa
# ruff: noqa
# type: ignore
"""add_cascade_for_problem

Revision ID: 6340448767fb
Revises: 3c683bc423ad
Create Date: 2025-12-03 15:29:43.459483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6340448767fb'
down_revision: Union[str, Sequence[str], None] = '3c683bc423ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('option', 'problem_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('option_problem_id_fkey'), 'option', type_='foreignkey')
    op.create_foreign_key(None, 'option', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.alter_column('problem', 'problemset_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('problem_problemset_id_fkey'), 'problem', type_='foreignkey')
    op.create_foreign_key(None, 'problem', 'problemset', ['problemset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.create_foreign_key(op.f('problem_problemset_id_fkey'), 'problem', 'problemset', ['problemset_id'], ['id'])
    op.alter_column('problem', 'problemset_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.create_foreign_key(op.f('option_problem_id_fkey'), 'option', 'problem', ['problem_id'], ['id'])
    op.alter_column('option', 'problem_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
