# noqa
# ruff: noqa
# type: ignore
"""rm_stat

Revision ID: ecb02d541c23
Revises: 6340448767fb
Create Date: 2025-12-09 16:22:53.436311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecb02d541c23'
down_revision: Union[str, Sequence[str], None] = '6340448767fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_record')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_record',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('problem_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correct_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_attempt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], name=op.f('answer_record_problem_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('answer_record_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'problem_id', name=op.f('answer_record_pkey'))
    )
    # ### end Alembic commands ###
