# noqa
# ruff: noqa
# type: ignore
"""time_field_for_tables

Revision ID: fb0fab9109cc
Revises: c269a80e89c8
Create Date: 2025-12-28 10:32:27.813093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fb0fab9109cc'
down_revision: Union[str, Sequence[str], None] = 'c269a80e89c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('problem', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tag', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tag', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'updated_at')
    op.drop_column('tag', 'created_at')
    op.drop_column('problem', 'updated_at')
    op.drop_column('problem', 'created_at')
    # ### end Alembic commands ###
