# noqa
# ruff: noqa
# type: ignore
"""migrate_problem_details_to_jsonb

Revision ID: fd4be665eb58
Revises: ecb02d541c23
Create Date: 2025-12-10 04:58:22.719553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd4be665eb58'
down_revision: Union[str, Sequence[str], None] = 'ecb02d541c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option')
    op.add_column('problem', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('problem', sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index('ix_problem_details_gin', 'problem', ['details'], unique=False, postgresql_using='gin')
    op.add_column('problemset', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('problemset', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('problemset', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problemset', 'created_at')
    op.drop_column('problemset', 'description')
    op.drop_column('problemset', 'created_by')
    op.drop_index('ix_problem_details_gin', table_name='problem', postgresql_using='gin')
    op.drop_column('problem', 'explanation')
    op.drop_column('problem', 'details')
    op.create_table('option',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('problem_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], name=op.f('option_problem_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('option_pkey'))
    )
    # ### end Alembic commands ###
